[tool.poetry]
name = "todo-list"
version = "0.1.0"
description = ""
package-mode = false

[tool.poetry.dependencies]
python = ">=3.14"
django = ">=6.0.3,<7.0.0"
django-summernote = "^0.8.20.0"
pillow = "^12.1.1"
django-cleanup = "^9.0.0"

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
